services:
  gen:
    build: .
    container_name: gen_queries
    command: ["./gen_queries", "12", "10", "2", "6"]  # 12 users, 10 items, 6 features, 3 queries
    volumes:
      - ./data:/app/data
    networks:
      - mpc_net

  p2:
    build: .
    container_name: p2
    environment:
      - ROLE=p2
    depends_on:
      gen:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
    networks:
      - mpc_net

  p0:
    build: .
    container_name: p0
    environment:
      - ROLE=p0
    depends_on:
      - p2
      - p1
    volumes:
      - ./data:/app/data
    networks:
      - mpc_net

  p1:
    build: .
    container_name: p1
    environment:
      - ROLE=p1
    depends_on:
      - p2
    volumes:
      - ./data:/app/data
    networks:
      - mpc_net

networks:
  mpc_net:
    driver: bridge
